nginx:
    ports:
        - "80:80"
    links:
        - fpm
    build: docker/nginx
fpm:
    ports:
        - "9000:9000"

    build: docker/php-fpm
    # seems like fpm receive the full path from nginx
    # and try to find the files in this dock, so it must
    # be the same as nginx.root
    volumes:
       - ./:/var/www/html
