nginx:
    build: .
    ports:
        - "80:80"
    links:
        - fpm
fpm:
    image: php:7.0-fpm
    ports:
        - "9000:9000"

    # seems like fpm receive the full path from nginx
    # and try to find the files in this dock, so it must
    # be the same as nginx.root
    volumes:
        - ./:/complex/path/to/files/
