create_link:
  path: /api/link
  methods: POST
  defaults:
    _controller: link_service.infrastructure.api.controller.create_link_controller:createAction

update_link:
  path: /api/link
  methods: PUT
  defaults:
    _controller: link_service.infrastructure.api.controller.update_link_controller:updateAction

delete_link:
  path: /api/link
  methods: DELETE
  defaults:
    _controller: link_service.infrastructure.api.controller.delete_link_controller:deleteAction

shorten_link:
  path: /
  methods: POST
  defaults:
    _controller: link_service.infrastructure.web.controller.page_controller:shortenLinkAction

page:
  path: /
  methods: GET
  defaults:
    _controller: link_service.infrastructure.web.controller.page_controller:viewAction

bundles_router:
  path: /bundles/{url}
  methods: GET
  defaults:
    _controller: link_service.infrastructure.web.controller.bundles_router_controller:route
  requirements:
    url: ".*"

transform_route:
  path: /{url}
  defaults:
    _controller: link_service.infrastructure.api.controller.redirect_controller:redirectAction
  requirements:
    url: ".*"
