services:
  link_service.infrastructure.api.controller.redirect_controller:
    class: LinkService\Infrastructure\Api\Controller\RedirectController
    arguments:
      - '@link_service.application.get_trackable_link_handler'

  link_service.infrastructure.api.controller.create_link_controller:
    class: LinkService\Infrastructure\Api\Controller\CreateLinkController
    arguments:
      - '@link_service.application.create_link_handler'

  link_service.infrastructure.api.controller.delete_link_controller:
    class: LinkService\Infrastructure\Api\Controller\DeleteLinkController
    arguments:
      - '@link_service.application.delete_link_handler'

  link_service.infrastructure.api.controller.update_link_controller:
    class: LinkService\Infrastructure\Api\Controller\UpdateLinkController
    arguments:
      - '@link_service.application.update_link_handler'

  link_service.application.get_trackable_link_handler:
    class: LinkService\Application\GetTrackableLinkHandler
    arguments:
      - '@link_service.infrastructure.persistence.trackable_link_repository'
      - '@link_service.infrastructure.persistence.mysql.mysql_click_repository'

  link_service.application.create_link_handler:
    class: LinkService\Application\CreateLinkHandler
    arguments:
      - '@link_service.infrastructure.persistence.trackable_link_repository'

  link_service.application.delete_link_handler:
    class: LinkService\Application\DeleteLinkHandler
    arguments:
      - '@link_service.infrastructure.persistence.trackable_link_repository'

  link_service.application.update_link_handler:
    class: LinkService\Application\UpdateLinkHandler
    arguments:
      - '@link_service.infrastructure.persistence.trackable_link_repository'

  link_service.infrastructure.persistence.trackable_link_repository:
    class: LinkService\Infrastructure\Persistence\Redis\RedisTrackableLinkRepository
    arguments:
      - '@redis_client'

  link_service.infrastructure.persistence.mysql.mysql_click_repository:
    class: LinkService\Infrastructure\Persistence\Mysql\MysqlClickRepository
    arguments:
      - '@pdo_client'

  redis_client:
    class: Predis\Client
    arguments:
      - '%redis_dsn%'
      - { prefix: "linkservice:" }

  pdo_client:
    class: PDO
    arguments:
      - 'mysql:host=%database_host%;dbname=%database_name%'
      - '%database_user%'
      - '%database_password%'